// WebGpuWater - appearance controls for foam generated by the river-fluid bake.
#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;

namespace AbstractOcclusion.WebGpuWater.Editor
{
    [CustomEditor(typeof(WaterRiverFoam))]
    [CanEditMultipleObjects]
    internal sealed class WaterRiverFoamEditor : UnityEditor.Editor
    {
        const string StrengthPropertyName = "strength";
        const string PatternSizePropertyName = "patternSize";
        const string EdgeFeatherPropertyName = "edgeFeather";
        const string CoreCutPropertyName = "coreCut";
        const string InspectorHelp =
            "Controls the look of solver-generated foam. Coverage comes from River Fluid; the " +
            "assigned Water Volume supplies the existing foam texture and colour.";
        const string MissingFluidWarning =
            "Add River Fluid and bake it before enabling river foam.";
        const string MissingBakeWarning =
            "River Fluid has no valid bake. Use Bake Settled Fluid on that component.";
        const string MissingVolumeWarning =
            "Assign a Water Volume on River Surface so foam receives the established water look " +
            "and participates in the after-fog overlay.";
        const string BakeStatusFormat = "Using fluid bake {0} x {1}, river length {2:0.##} m";

        public override void OnInspectorGUI()
        {
            serializedObject.Update();
            EditorGUILayout.HelpBox(InspectorHelp, MessageType.None);
            WaterEditorUI.SubHeading("Appearance");
            DrawProperty(StrengthPropertyName);
            DrawProperty(PatternSizePropertyName);
            DrawProperty(EdgeFeatherPropertyName);
            DrawProperty(CoreCutPropertyName);
            serializedObject.ApplyModifiedProperties();
            DrawWarningsAndStatus();
        }

        void DrawProperty(string propertyName)
            => EditorGUILayout.PropertyField(serializedObject.FindProperty(propertyName));

        void DrawWarningsAndStatus()
        {
            if (targets.Length != 1) return;
            var foam = (WaterRiverFoam)target;
            WaterRiverSurface surface = foam.GetComponent<WaterRiverSurface>();
            WaterRiverFluid fluid = foam.GetComponent<WaterRiverFluid>();
            if (fluid == null)
                EditorGUILayout.HelpBox(MissingFluidWarning, MessageType.Warning);
            else if (fluid.BakeData == null || !fluid.BakeData.IsValid)
                EditorGUILayout.HelpBox(MissingBakeWarning, MessageType.Warning);
            if (surface == null || surface.WaterVolume == null)
                EditorGUILayout.HelpBox(MissingVolumeWarning, MessageType.Warning);
            if (fluid?.BakeData == null || !fluid.BakeData.IsValid) return;
            EditorGUILayout.LabelField(
                string.Format(BakeStatusFormat,
                              fluid.BakeData.LateralResolution,
                              fluid.BakeData.LongitudinalResolution,
                              fluid.BakeData.RiverLength),
                EditorStyles.miniLabel);
        }
    }
}
#endif
