// WebGpuWater - pool walls & floor (Unity 6 / URP port)
// The pool mesh is generated by the scene builder already in world coordinates:
// floor at y = -1, walls rising to y = 2/12, spanning x,z in [-1, 1].
// Keeps the original analytic look (refracted-light diffuse, projected
// caustics, rim shadow) but is now a proper URP forward pass, so it also RECEIVES
// real shadows cast by interactable objects from the scene's directional light.
Shader "AbstractOcclusion/WebGpuWater/AnalyticPool"
{
    Properties
    {
        [Enum(UnityEngine.Rendering.CullMode)] _Cull ("Cull", Float) = 2 // Back
        _TilesTiling ("Tiles Tiling", Vector) = (1,1,0,0)
        [Toggle(_AUTOTILE)] _AutoTileByFace ("Auto Tile By Face Size", Float) = 0
        [Toggle(_USECUSTOMTILES)] _UseCustomTiles ("Use Custom Tiles Texture", Float) = 0
        _BaseMap ("Custom Tiles", 2D) = "white" {}
        [Normal] _BumpMap ("Normal Map", 2D) = "bump" {}
        _BumpScale ("Normal Scale", Float) = 1
        _ObjectShadowStrength ("Object Shadow Strength", Range(0,1)) = 0.6
        // Matches WaterReceiver's caustic controls. Default 2 reproduces the legacy baked
        // strength, so existing pools look unchanged until tuned (WaterReceiver defaults to 4,
        // but the pool's caustic term also carries refracted diffuse + rim occlusion, so the
        // two strength values are not directly comparable).
        _CausticStrength ("Caustic Strength", Range(0,8)) = 2
        _CausticTint ("Caustic Tint", Color) = (1,1,1,1)
    }
    SubShader
    {
        Tags { "RenderType"="Opaque" "Queue"="Geometry" "RenderPipeline"="UniversalPipeline" }
        Pass
        {
            Name "ForwardLit"
            Tags { "LightMode"="UniversalForward" }
            Cull [_Cull]
            ZWrite On
            ZTest LEqual

            // Mark these pixels so the screen-space WaterCausticProjection pass SKIPS them (this shader
            // already adds caustics in-shader below - the pass must not add them a second time). Bit 3 is
            // in URP's user stencil range (StencilUsage.UserMask = bits [0,3]); WriteMask 8 touches only it.
            Stencil { Ref 8 WriteMask 8 Comp Always Pass Replace }

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma target 4.0
            // ONE 4-way set, exactly as URP's own Lit.shader declares it. URP sets these keywords
            // mutually exclusively, so two independent pragmas were compiling a 3x2 cross product in
            // which both *_SCREEN combinations are unreachable states.
            // _fragment on all of them: every consumer of these keywords lives in frag, so the
            // unscoped forms were also compiling a separate, byte-identical vertex program per combination.
            #pragma multi_compile_fragment _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _MAIN_LIGHT_SHADOWS_SCREEN
            #pragma multi_compile_fragment _ _SHADOWS_SOFT _SHADOWS_SOFT_LOW _SHADOWS_SOFT_MEDIUM _SHADOWS_SOFT_HIGH
            #pragma shader_feature_local_fragment _USECUSTOMTILES
            #pragma shader_feature_local_fragment _AUTOTILE

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"
            // Analytic helpers (GetWallShadeSplit etc). Uses legacy tex2D/sampler2D, which
            // resolve via the auto-included HLSLSupport in URP HLSLPROGRAM blocks.
            #include "WaterCommon.hlsl"
            #include "WaterFog.hlsl"
            #include "WaterVolume.hlsl"

            #define UNDERWATER_WALL_BOOST 1.2 // walls read a touch brighter than the surface underwater

            float _ObjectShadowStrength;
            sampler2D _BaseMap;   // optional per-material tiles albedo (used when _USECUSTOMTILES is on)
            sampler2D _BumpMap;   // pool-wall normal map (defaults flat, so untouched materials are unchanged)
            float4 _TilesTiling;  // xy = tile repeat across the pool faces
            float _BumpScale;
            float _CausticStrength; // per-material caustic gain (see GetWallShadeSplit); default 2 = legacy
            float4 _CausticTint;    // per-material caustic colour, applied like WaterReceiver

            struct appdata { float4 vertex : POSITION; };
            struct v2f
            {
                float4 pos      : SV_POSITION;
                float3 position : TEXCOORD0; // POOL space, for the analytic wall look
                float3 worldPos : TEXCOORD1; // world space, for shadows + fog
            };

            v2f vert(appdata v)
            {
                v2f o;
                float3 poolPos = v.vertex.xyz;          // pool mesh authored in [-1,1]
                float3 worldPos = PoolToWorld(poolPos); // placed by the volume frame
                o.position = poolPos;
                o.worldPos = worldPos;
                o.pos = TransformWorldToHClip(worldPos);
                return o;
            }

            half4 frag(v2f i) : SV_Target
            {
                // Per-material tiles + tiling + normal map on the wall faces, reusing the shared
                // analytic shading (AO / caustics / rim). Defaults reproduce the old look exactly:
                // global _Tiles, tiling (1,1), flat normal.
                float2 wallUV; float3 faceN, wallT, wallB;
                WallSurface(i.position, wallUV, faceN, wallT, wallB);
                // Auto Tile By Face Size: scale each face's UV by its WORLD size along the U/V
                // axes (from the volume extent), so tiles keep an even density on the floor and
                // every wall even when the pool is rectangular or deep. _TilesTiling is then a
                // tiles-per-world-unit density. Off = the raw pool-space UV (legacy).
            #ifdef _AUTOTILE
                float3 volExtent = VolumeExtentSafe();
                float2 faceWorld = float2(dot(abs(wallT), volExtent), dot(abs(wallB), volExtent));
                float2 tileUV = wallUV * faceWorld * _TilesTiling.xy;
            #else
                float2 tileUV = wallUV * _TilesTiling.xy;
            #endif
            #ifdef _USECUSTOMTILES
                float3 albedo = tex2D(_BaseMap, tileUV).rgb;
            #else
                float3 albedo = tex2D(_Tiles, tileUV).rgb;
            #endif
                float3 nmap = UnpackNormalScale(tex2D(_BumpMap, tileUV), _BumpScale);
                float3 wallN = normalize(nmap.x * wallT + nmap.y * wallB + nmap.z * faceN);

                // Base analytic wall shade, then projected caustics added with this material's own
                // strength + tint (mirrors WaterReceiver). At strength 2 / white tint this equals the
                // legacy analytic wall shade, so the additive split changes nothing until tuned.
                // Position derivatives hoisted here (uniform flow): GetWallShadeSplit's caustic tap
                // sits inside a per-fragment waterline branch, undefined for implicit-derivative
                // samples in WGSL.
                float3 poolDdx = ddx(i.position);
                float3 poolDdy = ddy(i.position);
                float wallCaustic;
                float wallShade = GetWallShadeSplit(i.position, wallN, poolDdx, poolDdy, wallCaustic);
                float3 color = albedo * wallShade;

                // Footprint + sim surface height fetched up front: the underwater object shadow below
                // needs both. i.position is already pool space. Manual bilinear because WebGPU
                // point-samples float32 textures (blocky waterline cut otherwise).
                float inside = FootprintMaskPool(i.position);
                float4 info = SampleWaterBilinear(i.position.xz * 0.5 + 0.5);
                bool underwater = (inside > 0.5 && i.position.y < info.r);

                // Main light + shadow fetched up front so caustics can be gated by it below.
                float4 shadowCoord = TransformWorldToShadowCoord(i.worldPos);
                Light mainLight = GetMainLight(shadowCoord);
                float urpShadow = mainLight.shadowAttenuation;

                // Below the surface a caster's shadow must follow the REFRACTED light like the caustics
                // do - the un-refracted shadow map lands offset underwater (the reported caustic-border
                // vs shadow mismatch) and carries OTHER bodies' casters across pool boundaries. The
                // occluder pass writes this body's silhouettes into the caustic green channel along that
                // same projection (1 = lit where nothing is submerged); use it below the waterline, keep
                // the real shadow map for the sunlit rim above. The shadow-map fallback remains only for
                // setups without the occluder shader wired (_CausticOccluderActive 0).
                float2 occCuv = ProjectCausticUV(i.position, WorldDirToPool(-refract(-_LightDir, float3(0.0, 1.0, 0.0), IOR_AIR / IOR_WATER)));
                float occluderGreen = tex2D(_CausticTex, occCuv).g;
                // Green is the occluder's depth: this floor/wall point is shadowed only below that
                // depth. Four extra explicit-LOD taps = the shared distance-grown PCF penumbra
                // (WaterShared); radius 0 collapses onto the centre = the legacy look.
                float occRadius = OccluderPenumbraRadiusUV(i.position.y);
                float4 occGreens = float4(
                    tex2Dlod(_CausticTex, float4(occCuv + OCCLUDER_PCF_TAP0 * occRadius, 0.0, 0.0)).g,
                    tex2Dlod(_CausticTex, float4(occCuv + OCCLUDER_PCF_TAP1 * occRadius, 0.0, 0.0)).g,
                    tex2Dlod(_CausticTex, float4(occCuv + OCCLUDER_PCF_TAP2 * occRadius, 0.0, 0.0)).g,
                    tex2Dlod(_CausticTex, float4(occCuv + OCCLUDER_PCF_TAP3 * occRadius, 0.0, 0.0)).g);
                float occluderShadow = OccluderLitFromGreenPCF(i.position.y, occluderGreen, occGreens);
                float objectShadow = (_CausticOccluderActive > 0.5 && underwater) ? occluderShadow : urpShadow;
                // wallCaustic already carries the green occlusion, so when the pass is active the
                // refracted shadow is baked into it - don't also multiply the un-refracted shadow map on top.
                float causticShadowGate = (_CausticOccluderActive > 0.5) ? 1.0 : urpShadow;

                // Soft, art-directed object shadow on the base pool colour (unchanged in full sun).
                color *= lerp(1.0, objectShadow, _ObjectShadowStrength);
                // Caustics are refracted SUNLIGHT: gate them so they vanish under a caster.
                color += albedo * _CausticTint.rgb * (wallCaustic * _CausticStrength * causticShadowGate);

                if (underwater) color *= UnderwaterViewTint() * UNDERWATER_WALL_BOOST;

                // One surface height: the sampled sim surface converted to world Y, the same
                // height the waterline cut above uses. Downwelling and fog measure depth
                // against it rather than the flat _VolumeCenter.y plane (so a pool at any Y
                // is handled by its own volume frame, and cut/fog never disagree).
                float surfaceY = PoolToWorld(float3(i.position.x, info.r, i.position.z)).y;

                // Downwelling darkening: deeper walls/floor read darker and hue-shifted.
                // This also fades the floor caustics baked into the wall colour with depth.
                if (inside > 0.5) color *= DownwellingAttenuation(i.worldPos.y, surfaceY);

                // depth absorption (shared fog; measured against the sampled surface Y)
                if (inside > 0.5)
                    color = ApplyWaterFog(color, WaterPathLength(i.worldPos, _WorldSpaceCameraPos, surfaceY),
                                          WaterInscatterColor(normalize(_WorldSpaceCameraPos - i.worldPos),
                                                              _LightDir, _SunColor, 0.0));

                return half4(color, 1);
            }
            ENDHLSL
        }

        // Depth prepass passes so the walls populate _CameraDepthTexture under EITHER a depth or a
        // depth-normals (SSAO) prepass - without them the volumetric god rays, which occlude per marched
        // step against the camera depth, drew straight over the walls. CRITICAL: the pool mesh is authored
        // in POOL space [-1,1] and placed by the volume frame (PoolToWorld), NOT the object transform, so
        // these passes MUST place it the same way as ForwardLit. Using TransformObjectToHClip writes a
        // stale 1x1 box that the god-ray depth then reads. Caustics live in ForwardLit and are unaffected.
        // (No ShadowCaster: the pool box does not cast scene shadows, matching the original behaviour.)
        Pass
        {
            Name "DepthOnly"
            Tags { "LightMode"="DepthOnly" }
            ZWrite On ColorMask 0 Cull [_Cull]

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "WaterCommon.hlsl"
            #include "WaterVolume.hlsl" // PoolToWorld: place the pool-space mesh through the volume frame

            struct A { float4 positionOS:POSITION; };
            struct V { float4 positionCS:SV_POSITION; };

            V vert(A IN) { V o; o.positionCS = TransformWorldToHClip(PoolToWorld(IN.positionOS.xyz)); return o; }
            half4 frag(V IN) : SV_Target { return 0; }
            ENDHLSL
        }

        Pass
        {
            Name "DepthNormals"
            Tags { "LightMode"="DepthNormals" }
            ZWrite On Cull [_Cull]

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "WaterCommon.hlsl"
            #include "WaterVolume.hlsl" // PoolToWorld / PoolNormalToWorld: the volume frame

            struct A { float4 positionOS:POSITION; float3 normalOS:NORMAL; };
            struct V { float4 positionCS:SV_POSITION; float3 normalWS:TEXCOORD0; };

            V vert(A IN)
            {
                V o;
                o.positionCS = TransformWorldToHClip(PoolToWorld(IN.positionOS.xyz));
                o.normalWS = PoolNormalToWorld(IN.normalOS);
                return o;
            }
            half4 frag(V IN) : SV_Target { return half4(normalize(IN.normalWS), 0.0); }
            ENDHLSL
        }
    }
}
